name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run:
        sudo apt-get update;
        sudo apt-get install libglfw3-dev;
    - name: Configure CMake
      working-directory: examples/empty_3D_scene
      run: cmake -B build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: Build
      working-directory: examples/empty_3D_scene/build
      run: make -j$(nproc)
    - name: Compile Unit test
      working-directory: examples/test_cgp/
      run: make -j$(nproc)
    - name: Run Unit test
      working-directory: examples/test_cgp/
      run: ./test_cgp